checksum

diff --git a/.github/workflows/checksum_test.yaml b/.github/workflows/checksum_test.yaml
--- a/.github/workflows/checksum_test.yaml
+++ b/.github/workflows/checksum_test.yaml
@@ -25,14 +25,12 @@ jobs:
           SUM=$PERMISSIONS_CHECKSUM
           QUICK_TRIM=${SUM::64} #quick_trim is used to get rid of the tailing "-" after the checksum
           echo $QUICK_TRIM
-          CHECK=$( cat permissions_checksum.txt )
-          echo $CHECK
-          CHECKSUM=${CHECK::64}
+          CHECKSUM=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
           if [["$QUICK_TRIM == $CHECKSUM"]]; then
-                echo "******SUCCESS********" 
+            echo "******SUCCESS********" 
           else 
-                echo "*******FAILURE*******"
-                echo "image checksum: $QUICK_TRIM"
-                echo "correct image checksum: $CHECKSUM"
-                #exit 1
+            echo "*******FAILURE*******"
+            echo "image checksum: $QUICK_TRIM"
+            echo "correct image checksum: $CHECKSUM"
+            #exit 1
           fi
